openapi: 3.0.0
info:
  title: Proxpay API
  version: 1.0.0
servers:
  - url: https://stg-api.proxpay.co/spark
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []      
tags:
  - name: transactions > withdrawals
  - name: transactions > deposits
  - name: customers
  - name: merchants
  - name: users
paths:
  /transactions/withdrawals/refno/{refno}:
    get:
      tags:
        - transactions > withdrawals
      summary: Get Withdrawal By Refno
      security:
        - bearerAuth: []
      parameters:
        - name: apikey
          in: header
          schema:
            type: string
          example: '{{apikey}}'
        - name: refno
          in: path
          schema:
            type: string
          required: true
          example: PS202201180002
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /transactions/withdrawals:
    post:
      tags:
        - transactions > withdrawals
      summary: Create Withdrawal (Customer / HQ / HQ International)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                amount: 200
                refno: PSHQW202201180002
                merchant_id: 3
                customer_id: 2 (Only use for Customer Withdrawal)
                prefer_currency: USD (Only use for HQ International Withdrawal)
      security:
        - bearerAuth: []
      parameters:
        - name: apikey
          in: query
          schema:
            type: string
          example: '{{apikey}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /transactions/deposits:
    post:
      tags:
        - transactions > deposits
      summary: Create Deposit
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                amount: 20000
                refno: PS202201180002
                merchant_id: 3
                customer_id: 15 (Only use for Customer Deposit)
      security: 
        - bearerAuth: []
      parameters:
        - name: apikey
          in: header
          schema:
            type: string
          example: '{{apikey}}'
        - name: apikey
          in: query
          schema:
            type: string
          example: '{{apikey}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /customers/ref-customer-id/{ref}:
    get:
      tags:
        - customers
      summary: Get Customer By Customer Ref. No.
      security:
        - bearerAuth: []
      parameters:
        - name: apikey
          in: header
          schema:
            type: string
          example: '{{apikey}}'
        - name: ref
          in: path
          schema:
            type: integer
          required: true
          example: '000020'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {
              "id": 99,
              "ref_customer_id": "XXXX0002",
              "name": "John Doe",
              "balance": 0,
              "merchant": {
                  "id": 98,
                  "name": "Simple Merchant"
              },
              "bank_name": "SCB",
              "book_bank_number": "0987654321",
              "book_bank_name": "John Doe",
              "created_at": "2022-03-15T01:50:57Z"
              }
  /customers:
    post:
      tags:
        - customers
      summary: Create Customer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                ref_customer_id: PSC00111
                merchant_id: 10
                name: Panupong Chantaklang
                bank_name: SCB
                book_bank_number: '2345678901'
                book_bank_name: Panupong Chantaklang
                book_bank_branch: รังสิต
      security:
        - bearerAuth: []
      parameters:
        - name: apikey
          in: header
          schema:
            type: string
          example: '{{apikey}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /customers/{id}:
    put:
      tags:
        - customers
      summary: Update Customer by Customer Ref.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                ref_customer_id: C0001
                name: John Doe
                bank_name: SCB
                book_bank_number: '12341234'
                book_bank_name: John Doe
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '122'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
/customers/{id}:
    put:
      tags:
        - customers
      summary: Update Customer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                ref_customer_id: C0001
                name: John Doe
                bank_name: SCB
                book_bank_number: '12341234'
                book_bank_name: 'John Doe'
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '122'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {
    "id": 99,
    "ref_customer_id": "SMPC0002",
    "name": "John Doe",
    "balance": 0,
    "merchant": {
        "id": 98,
        "name": "Simple Merchant"
    },
    "bank_name": "SCB",
    "book_bank_number": "123456789",
    "book_bank_name": "John Doe",
    "created_at": "2022-03-15T01:50:57Z"
}
  /merchants/ref-merchant-id/{ref}:
    get:
      tags:
        - merchants
      summary: Get Merchant By Customer Ref. No.
      security:
        - bearerAuth: []
      parameters:
        - name: apikey
          in: header
          schema:
            type: string
          example: '{{apikey}}'
        - name: ref
          in: path
          schema:
            type: integer
          required: true
          example: '34758'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {
    "id": 98,
    "ref_merchant_id": "123456",
    "name": "Simple Merchant",
    "balance": 999570,
    "bank_name": "SCB",
    "book_bank_number": "8000000000",
    "book_bank_name": "Simple Merchant",
    "book_bank_branch": "Rangsit",
    "deposit_fee_rate": 0.025,
    "withdraw_fee_rate": 0.008,
    "company_name": "Simple ",
    "company_address": "1",
    "company_website": "https://www.some-company.com",
    "contact_name": "nan",
    "contact_phone": "029999999",
    "contact_email": "contact@email.com",
    "sales_name": "x",
    "available_services": "promptpay,e_wallet",
    "created_at": "2022-03-15T01:48:24Z"
}
  /users/login:
    post:
      tags:
        - users
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: '{{user}}'
                password: '{{pass}}'
      parameters:
        - name: apikey
          in: header
          schema:
            type: string
          example: '{{apikey}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
